baseURL = 'https://takak8101.github.io/'
languageCode = 'en-us'
title = "kondy(sunflo_hn)"

theme = "beautifulhugo"

publishDir = "docs"

[Params]
  # subtitle = "test"
  # logo = "img/IMG_0248.jpg" # Expecting square dimensions
  # favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "kondy"
  twitter = "https://twitter.com/sunflo_hn"
