baseURL = 'https://takak8101.github.io/'
languageCode = 'en-us'
title = "kondy's portfolio"

theme = "beautifulhugo"

publishDir = "docs"

[Params]
  subtitle = "test"
  # logo = "img/avatar-icon.png" # Expecting square dimensions
  # favicon = "img/favicon.ico"
  dateFormat = "October 31, 2023"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "kondy"
  # github = "uzimihsr"
  twitter = "https://twitter.com/sunflo_hn"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 3